AWSTemplateFormatVersion: '2010-09-09'
Description: ARR Compute - Red/Blue ASGs in private subnets with CloudWatch Logs + cfn-signal

Parameters:
  PrivateSubnetA:
    Type: String
  PrivateSubnetB:
    Type: String

  EC2SecurityGroup:
    Type: String

  InstanceProfileName:
    Type: String

  InstanceRoleName:
    Type: String
    Default: S3-ARR-role

  RedTargetGroupArn:
    Type: String
  BlueTargetGroupArn:
    Type: String

  BucketName:
    Type: String
    Default: arr-bucket12398

  LogGroupPrefix:
    Type: String
    Default: /arr/advanced-routing

Resources:

# -------------------------------
# CloudWatch Log Groups
# -------------------------------
  RedLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "${LogGroupPrefix}/red"
      RetentionInDays: 7

  BlueLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "${LogGroupPrefix}/blue"
      RetentionInDays: 7

# -------------------------------
# CloudWatch Logs IAM Policy
# -------------------------------
  CloudWatchLogsPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "arr-cwlogs-${AWS::StackName}"
      Roles:
        - !Ref InstanceRoleName
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:DescribeLogStreams
              - logs:PutLogEvents
            Resource: "*"

# -------------------------------
# RED Launch Template
# -------------------------------
  RedLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub "arr-red-lt-${AWS::StackName}"
      LaunchTemplateData:
        ImageId: ami-0f3caa1cf4417e51b
        InstanceType: t2.micro
        MetadataOptions:
          HttpTokens: required
        IamInstanceProfile:
          Name: !Ref InstanceProfileName
        SecurityGroupIds:
          - !Ref EC2SecurityGroup
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash

            exec > >(tee /var/log/user-data.log | logger -t user-data -s 2>/dev/console) 2>&1

            yum update -y
            yum install -y httpd awscli amazon-cloudwatch-agent

            systemctl enable httpd
            systemctl start httpd

            mkdir -p /var/www/html/red

            cd /var/www/html/red
            aws s3 cp s3://${BucketName}/hw-red.css ./
            aws s3 cp s3://${BucketName}/hw-red-py.css ./
            aws s3 cp s3://${BucketName}/python.png ./
            aws s3 cp s3://${BucketName}/apache.svg ./
            aws s3 cp s3://${BucketName}/red-index.html ./index.html

            EC2AZ=$(TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"` && curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/meta-data/placement/availability-zone)
            echo '<center><h1>This Amazon EC2 instance is located in Availability Zone: AZID </h1></center>' > /var/www/html/red/index.txt
            sed "s/AZID/$EC2AZ/" /var/www/html/red/index.txt >> /var/www/html/red/index.html
            
            cd /var/www/html
            aws s3 cp s3://${BucketName}/hw-red.css ./
            aws s3 cp s3://${BucketName}/hw-red-py.css ./
            aws s3 cp s3://${BucketName}/python.png ./
            aws s3 cp s3://${BucketName}/apache.svg ./
            aws s3 cp s3://${BucketName}/red-root-index.html ./index.html

            sed "s/AZID/$EC2AZ/" /var/www/html/red/index.txt >> /var/www/html/index.html

            systemctl restart httpd

            # Configure CloudWatch Agent
            cat >/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json <<EOF
            {
              "logs": {
                "logs_collected": {
                  "files": {
                    "collect_list": [
                      { "file_path": "/var/log/cloud-init.log", "log_group_name": "${LogGroupPrefix}/red", "log_stream_name": "{instance_id}/cloud-init.log" },
                      { "file_path": "/var/log/cloud-init-output.log", "log_group_name": "${LogGroupPrefix}/red", "log_stream_name": "{instance_id}/cloud-init-output.log" },
                      { "file_path": "/var/log/messages", "log_group_name": "${LogGroupPrefix}/red", "log_stream_name": "{instance_id}/messages" },
                      { "file_path": "/var/log/user-data.log", "log_group_name": "${LogGroupPrefix}/red", "log_stream_name": "{instance_id}/user-data.log" },
                      { "file_path": "/var/log/httpd/access_log", "log_group_name": "${LogGroupPrefix}/red", "log_stream_name": "{instance_id}/httpd-access.log" },
                      { "file_path": "/var/log/httpd/error_log", "log_group_name": "${LogGroupPrefix}/red", "log_stream_name": "{instance_id}/httpd-error.log" }
                    ]
                  }
                }
              }
            }
            EOF

            /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config \
              -m ec2 \
              -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json \
              -s

            /opt/aws/bin/cfn-signal --exit-code $? --stack ${AWS::StackName} --resource RedASG --region ${AWS::Region}

# -------------------------------
# BLUE Launch Template
# -------------------------------
  BlueLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub "arr-blue-lt-${AWS::StackName}"
      LaunchTemplateData:
        ImageId: ami-0f3caa1cf4417e51b
        InstanceType: t2.micro
        MetadataOptions:
          HttpTokens: required
        IamInstanceProfile:
          Name: !Ref InstanceProfileName
        SecurityGroupIds:
          - !Ref EC2SecurityGroup
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash

            exec > >(tee /var/log/user-data.log | logger -t user-data -s 2>/dev/console) 2>&1

            yum update -y
            yum install -y httpd awscli amazon-cloudwatch-agent

            systemctl enable httpd
            systemctl start httpd

            mkdir -p /var/www/html/blue

            cd /var/www/html/blue
            aws s3 cp s3://${BucketName}/hw-blue.css ./
            aws s3 cp s3://${BucketName}/hw-blue-py.css ./
            aws s3 cp s3://${BucketName}/python.png ./
            aws s3 cp s3://${BucketName}/apache.svg ./
            aws s3 cp s3://${BucketName}/blue-index.html ./index.html

            EC2AZ=$(TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"` && curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/meta-data/placement/availability-zone)
            echo '<center><h1>This Amazon EC2 instance is located in Availability Zone: AZID </h1></center>' > /var/www/html/blue/index.txt
            sed "s/AZID/$EC2AZ/" /var/www/html/blue/index.txt >> /var/www/html/blue/index.html

            cd /var/www/html
            aws s3 cp s3://${BucketName}/hw-blue.css ./
            aws s3 cp s3://${BucketName}/hw-blue-py.css ./
            aws s3 cp s3://${BucketName}/python.png ./
            aws s3 cp s3://${BucketName}/apache.svg ./
            aws s3 cp s3://${BucketName}/blue-root-index.html ./index.html
             
            sed "s/AZID/$EC2AZ/" /var/www/html/blue/index.txt >> /var/www/html/index.html
             
            systemctl restart httpd

            cat >/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json <<EOF
            {
              "logs": {
                "logs_collected": {
                  "files": {
                    "collect_list": [
                      { "file_path": "/var/log/cloud-init.log", "log_group_name": "${LogGroupPrefix}/blue", "log_stream_name": "{instance_id}/cloud-init.log" },
                      { "file_path": "/var/log/cloud-init-output.log", "log_group_name": "${LogGroupPrefix}/blue", "log_stream_name": "{instance_id}/cloud-init-output.log" },
                      { "file_path": "/var/log/messages", "log_group_name": "${LogGroupPrefix}/blue", "log_stream_name": "{instance_id}/messages" },
                      { "file_path": "/var/log/user-data.log", "log_group_name": "${LogGroupPrefix}/blue", "log_stream_name": "{instance_id}/user-data.log" },
                      { "file_path": "/var/log/httpd/access_log", "log_group_name": "${LogGroupPrefix}/blue", "log_stream_name": "{instance_id}/httpd-access.log" },
                      { "file_path": "/var/log/httpd/error_log", "log_group_name": "${LogGroupPrefix}/blue", "log_stream_name": "{instance_id}/httpd-error.log" }
                    ]
                  }
                }
              }
            }
            EOF

            /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config \
              -m ec2 \
              -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json \
              -s

            /opt/aws/bin/cfn-signal --exit-code $? --stack ${AWS::StackName} --resource BlueASG --region ${AWS::Region}

# -------------------------------
# ASGs
# -------------------------------
  RedASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: PT20M
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: 1
        MaxBatchSize: 1
        PauseTime: PT10M
        WaitOnResourceSignals: true
    Properties:
      MinSize: '1'
      MaxSize: '2'
      DesiredCapacity: '1'
      VPCZoneIdentifier:
        - !Ref PrivateSubnetA
        - !Ref PrivateSubnetB
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300
      TargetGroupARNs:
        - !Ref RedTargetGroupArn
      LaunchTemplate:
        LaunchTemplateId: !Ref RedLaunchTemplate
        Version: !GetAtt RedLaunchTemplate.LatestVersionNumber

  BlueASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: PT20M
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: 1
        MaxBatchSize: 1
        PauseTime: PT10M
        WaitOnResourceSignals: true
    Properties:
      MinSize: '1'
      MaxSize: '2'
      DesiredCapacity: '1'
      VPCZoneIdentifier:
        - !Ref PrivateSubnetA
        - !Ref PrivateSubnetB
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300
      TargetGroupARNs:
        - !Ref BlueTargetGroupArn
      LaunchTemplate:
        LaunchTemplateId: !Ref BlueLaunchTemplate
        Version: !GetAtt BlueLaunchTemplate.LatestVersionNumber